# yml 파일 작성하기 
server:
  port: 9000 # port 번호
  servlet:
    context-path: /boot09 # context path 설정
    session:
      tracking-modes: cookie
      
      
#spring.datasource.driverClassName=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
#spring.datasource.driverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.datasource.url=jdbc:log4jdbc:mariadb://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
spring:
  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:oracle:thin:@localhost:1521:xe
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    username: scott
    password: tiger
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.boot09.**

management:
  endpoints:
    web:
      exposure:
        include: "*"









